/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Reserva;


import Cliente.*;
import static Cliente.FrmCliente.txtCorreo;
import Empleado.*;
import Controller.Controller;
import Models.Table;
import Views.View;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Empleado.Empleado; 
import static Empleado.FrmEmpleado.txtIdentificacion;
import static Empleado.FrmEmpleado.txtNombre;
import static Empleado.FrmEmpleado.txtSalario;
import static Empleado.FrmEmpleado.txtTelefono;
import static Reserva.FrmReserva.txtEstado;
import static Reserva.FrmReserva.txtFechaEntrada;
import static Reserva.FrmReserva.txtFechaSalida;
import static Reserva.FrmReserva.txtIdCliente;
import static Reserva.FrmReserva.txtPrecioTotal;
import static Reserva.FrmReserva.txtTipo;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;

/**
 *
 * @author jprod
 */
public class FrmBuscarReserva extends javax.swing.JInternalFrame implements View<Reserva> {  

    static Object getTblEmpleados() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
// Cambio del nombre de la clase
    private ReservaController controller;
    private Reserva reserva;
    private FrmReserva frmReserva;

    public FrmBuscarReserva() {
        initComponents();
        this.reserva = reserva;
        this.frmReserva = frmReserva;
        this.loadPuestos();  // Cambio del método
        this.controller = new ReservaController(this);  // Cambio del nombre de la clase
        this.controller.buscarTodo(); 
    }
     
    private void loadPuestos() {
   
    }
    
    @Override
    public void clear() {
        txtIdentificacion.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
//        txtPuesto.setText("");
        txtSalario.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Buscar Reserva");

        txtFiltro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserva", "Cliente", "Habitacion", "Entrada", "Salida", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservas.setColumnSelectionAllowed(true);
        tblReservas.getTableHeader().setReorderingAllowed(false);
        tblReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReservasMouseClicked(evt);
            }
        });
        tblReservas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblReservasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblReservas);
        tblReservas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/Icons/checkmark_korganizer (3).png"))); // NOI18N
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(457, 457, 457)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        Table.filter(this.tblReservas, txtFiltro.getText());
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tblReservasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblReservasKeyReleased

    }//GEN-LAST:event_tblReservasKeyReleased

    private void tblReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReservasMouseClicked
        if (evt.getClickCount() == 2) {
            int row = tblReservas.getSelectedRow();
            Object identificacion = tblReservas.getValueAt(row, 0);
            controller.tblReservas(identificacion);
        }
    }//GEN-LAST:event_tblReservasMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
            int row = tblReservas.getSelectedRow();
            Object identificacion = tblReservas.getValueAt(row, 0);
            controller.tblReservas(identificacion);
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void display(Reserva reserva) {
        //frmReserva.lblReserva.setText(String.valueOf(reserva.getNumeroReserva()));
        frmReserva.txtIdCliente.setText(String.valueOf(reserva.getIdCliente()));
        frmReserva.txtTipo.setSelectedItem(reserva.getTipoHabitacion());
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        frmReserva.txtFechaEntrada.setText(dateFormat.format(reserva.getFechaEntrada()));
        frmReserva.txtFechaSalida.setText(dateFormat.format(reserva.getFechaSalida()));
        frmReserva.txtEstado.setSelectedItem(reserva.getEstado());
        frmReserva.txtPrecioTotal.setText(String.valueOf(reserva.getPrecioTotal()));
    }

    @Override
    public void displayAll(Reserva[] regs) {
        DefaultTableModel tableModel = (DefaultTableModel) tblReservas.getModel();
        tableModel.setNumRows(0);
        for (Reserva reserva : regs) {
            Object[] data = reserva.toArrayObject();
            tableModel.addRow(data);
        }
        FrmBuscarReserva.tblReservas.setModel(tableModel);
    }

    @Override
    public void displayMessaje(String msj) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public boolean displayConfirmMessaje(String msj) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void displayErrorMessaje(String msj) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
