/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Servicio;



import Controller.Controller;
import Models.Table;
import Views.View;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Empleado.Empleado; 
import static Servicio.FrmServicio.txtCodigo;
import static Servicio.FrmServicio.txtDescripcion;
import static Servicio.FrmServicio.txtPrecio;
import static Servicio.FrmServicio.txtnombre;



/**
 *
 * @author rsand
 */
public class datosServicio extends javax.swing.JInternalFrame implements View<Servicio> {  
  
    private FrmServicio frmServicio;
    private Controller controller;
    private Servicio servicio;
    
    
    public datosServicio(FrmServicio frmServicio) {
       
        this.frmServicio = frmServicio;
        frmServicio.addObserver(this);
        
    }
    
    public datosServicio() {
        initComponents();
        this.servicio = servicio;
        this.loadPuestos();  
        this.controller = new ServicioControler(this); 
        this.controller.buscarTodo(); 
        
    }
         
     
    private void loadPuestos() {
   
    }
    
    @Override
    public void clear() {
        txtCodigo.setText("");
        txtnombre.setText("");
        txtDescripcion.setText("");
        txtPrecio.setText("");
    }

    @Override
    public void display(Servicio servicio){  
        frmServicio.txtCodigo.setText(String.valueOf(servicio.getCodigoServicio()));
        frmServicio.txtnombre.setText(servicio.getNombre());
        frmServicio.txtDescripcion.setText(servicio.getDescripcion());
        frmServicio.txtPrecio.setText(String.valueOf(servicio.getPrecio()));
        this.dispose();
    }
    
    @Override
    public void displayAll(Servicio[] regs) { 
        DefaultTableModel tableModel = (DefaultTableModel) tblServicio.getModel();
        tableModel.setNumRows(0);
        for (Servicio servicio : regs){
            Object[] datos = servicio.toArrayObject();
            tableModel.addRow(datos);
        }
        tblServicio.setModel(tableModel);
    }

    @Override
    public void displayMessaje(String msj) {
        JOptionPane.showMessageDialog(this, msj, "Información Importante", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void displayErrorMessaje(String msj) {
        JOptionPane.showMessageDialog(this, msj, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public boolean displayConfirmMessaje(String msj) {
        int option = JOptionPane.showConfirmDialog(this, msj, "Confirmación", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        return option == JOptionPane.YES_OPTION;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicio = new javax.swing.JTable();

        setClosable(true);

        txtFiltro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tblServicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Descripción", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServicio.setColumnSelectionAllowed(true);
        tblServicio.getTableHeader().setReorderingAllowed(false);
        tblServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServicioMouseClicked(evt);
            }
        });
        tblServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblServicioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblServicio);
        tblServicio.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        Table.filter(this.tblServicio, txtFiltro.getText());
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tblServicioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServicioKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int row = tblServicio.getSelectedRow();
            if (row > -1) {
                Object codigoServicio = tblServicio.getValueAt(row, 0);
                controller.Eliminar(new Empleado(codigoServicio.toString()));
            }
        }
    }//GEN-LAST:event_tblServicioKeyReleased

    private void tblServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServicioMouseClicked
        if (evt.getClickCount() == 2) {
            int row = tblServicio.getSelectedRow();
            Object codigoServicio = tblServicio.getValueAt(row, 0);
            controller.Buscar(codigoServicio);
        }
    }//GEN-LAST:event_tblServicioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblServicio;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

}
